<html>
<head>
	<title>견적시 참고 페이지</title> </head>

<body>

<BR><BR>
<br><br>
<a href="https://search.naver.com/search.naver?where=nexearch&sm=top_hty&fbm=1&ie=utf8&query=%ED%99%98%EC%9C%A8%EA%B3%84%EC%82%B0" target="_blank"> 환율 조회 ( 네이버 ) </a>
<BR><BR>
<a href="http://52.78.77.99/bbs/view.php?id=work_data&page=1&sn1=&divpage=1&sn=off&ss=on&sc=on&select_arrange=headnum&desc=asc&no=15" target="_blank"> 항공사코드 조회 ( 2자리 영문 ) </a>
<BR><BR>
<a href="https://www.airportal.go.kr/knowledge/airlines/KbAirline01.jsp?area=code" target="_blank"> 항공사코드 조회 2( 2자리 영문 ) </a>
<BR><BR>
<a href="https://www.airportal.go.kr/knowledge/airports/KfAirport01.jsp?area=name" target="_blank"> 공항코드 조회 ( 3자리 영문 ) </a>
<BR><BR>
<a href="https://ko.flightaware.com/live/findflight?origin=ENGM&destination=EPWA" target="_blank"> 항공편 검색 </a>
<BR><BR>
<a href="https://www.forwarder.kr/tariff/?quarter=2022_3&chg_type=%EC%95%88%EC%A0%84%EC%9A%B4%EC%86%A1%EC%9A%B4%EC%9E%84&stitle=%EB%B6%80%EC%82%B0%EC%8B%A0%ED%95%AD%EA%B8%B0%EC%A0%90&Send_region1=%EA%B2%BD%EC%83%81%EB%82%A8%EB%8F%84&Send_region2=&Send_region3=&tariff_region=&extra9=&extra8=&extra5=&extra10=" target="_blank"> 안전 운임 조회 ( 20'DV, 40'HC 운송료 조회 ) </a>
<BR><BR>
<a href="https://www.kas.co.kr/W/Business/Freight/Charge_02.aspx" target="_blank"> 수입 항공 창고료 계산 ( 인천 공항 입고시 ) </a>
<BR><BR>
<a href="http://service.aact.co.kr/form/AACT/AACT_INQUERY.aspx?tabs=B" target="_blank"> 수입 항공 창고료 계산 ( AACT ) </a>
<BR><BR>
<a href="https://www.hmm21.com/cms/business/kor/schedule/trade/index.jsp" target="_blank"> 항구 3 코드 찾기(HMM) </a>
<BR><BR>
<a href="http://www.hyojinlogis.com/?page_id=3325/" target="_blank"> 항구위치 (사진) </a>
<BR><BR>
<a href='https://www.metric-conversions.org/ko/volume/cubic-feet-to-cubic-meters.htm' target="_blank"> 큐빅 피트 계산기 (인터오션 용)</a>
<BR><BR>
<a href="https://www.google.com/search?q=lbs+kg+%EB%B3%80%ED%99%98&rlz=1C1CHZO_koKR1006KR1006&oq=&aqs=chrome.1.35i39i362l2j46i39i362j35i39i362l5.298851425j0j15&sourceid=chrome&ie=UTF-8"  target="_blank"> LBS - KG 변환 </a>
<BR><BR>
<a href='http://www.xn--910bu6kdmw.com/sub0305' target="_blank"> 화물운송 화물차(카고) 톤수별 적재함 사이즈</a>
<BR><BR>
<a href='https://www.forwarder.kr/curr/index.php?curr=cbm' target="_blank"> CBM 계산</a>
<BR><BR>
<a href='https://www.dhl.com/kr-ko/home/get-a-quote.html' target="_blank"> DHL 견적내기</a>
<BR><BR>
<a href='https://www.fedex.com/ko-kr/home.html#' target="_blank"> FEDEX 견적내기</a>
<BR><BR>
<a href='https://scsapps.ups.com/forwardinghub/us/en/quotes/' target="_blank"> UPS 견적내기 (로그인 필요)</a>
<BR><BR>
<a href='https://www.epost.go.kr/search.RetrieveIntegrationNewZipCdList.comm' target="_blank"> 우편번호 검색 (인천공항 우편번호 : 22382 ) </a>
<BR><BR>
<a href='https://www.fedex.com/ko-kr/about/holiday-schedule.html' target="_blank"> 휴일 조회 (국가별) - FEDEX </a>
<BR><BR>
<a href='https://www.forwarder.kr/curr/holiday.php' target="_blank"> 휴일 조회 (국가별) - FORWARDER.KR </a>
<BR><BR>


</body>
</html>